# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  postcard:
    image: postcard
    build:
      context: .
      dockerfile: Hackaton AWS 3/Source/postcard/Dockerfile
    ports:
      - 80:80
